---

# This is webhook for discord message
URL: ""

# Database configuration.
MySQL:
  # Here must go your IP of the connection to MySQL
  hostname: "45.58.127.223"
  # the username (in local mode is always 'root') of your hostname
  username: "u846_mLmLAonBFy"
  # If you do not have a password (if you are in local mode) do not change anything or the connection to MySQL will not be established
  password: "Gy1o@uF=.+Mb9VYbAemDXTdV"
  # The connection to create the tables, etc.
  database: "s846_Pocketmine"
  # Use it if the connection is not local
  port: 3306

# Global configuration of the functions of the server

Global:
# This configuration sets the time of each function (indicated by its name)
Cooldowns:
  # These are the cooldowns of the items, or other things within the server that can be modified to have more or less time
  EnderPearl: 15

  CombatTag: 25

  ArcherTag: 10
  
  OpArcherTag: 7

  Camuflaje: 150

  Apple: 25
  
  Archer_Mark: 8
  
  ROGUE_DELAY: 3
  
  Backstap: 8
  
  Refill: 300
  
  Snowball: 25
  
  OpBackstap: 12
  
  ResetItems: 120
  
  EggPorts: 30

  SpecialItem: 35

  StormBreaker: 150

  NinjaShear: 150

  LoggerBait: 150
  
  PotionCounter: 100

  AntiTrapper: 150

  AntiTrapperTarget: 30

  # These seconds are for the commands '/f home, /f stuck, /spawn and /logout'.
  Home: 20

  Stuck: 35

  Logout: 40
  
# Here you can modify the maximum values of the map factions (testing)
FactionsConfig:
  # Maximum players per map faction
  maxPlayers: 10
  # The edge of the end of map
  BorderLimit: 2000
  # Wilderness limit to build
  Wilderness: 400

# This configuration takes care of the entities available to spawners in the worlds
LevelManager:
  # This time is the time it takes for the spawner to create another entity
  EntitySpawnDelay: 400
  # Modifiable end world
  levelEndName: "end"
  # Modifiable nether world
  levelNetherName: "nether"
  
Worlds:
# modifiable name the nether world
  nether: "nether"
# modifiable name the end world
  end: "end"

commands:
    - "me"
    - "msg"
    - "tell"
    - "w"
    - "say"

commands_block:
    - "me"
    - "kill"
    - "suicide"
    
 # These blocks are the ones you must pass through to enter the End or exit the End
block_ids: ["119:0", "120:0"]

# These are the items that are blocked on the server
items_id: ["46:0", "259:0"]